/**
 * The Alive services client. One key, read from `.env.development`, and a discovery habit.
 *
 * The host comes from `ALIVE_SERVICES_URL`; `/discover` on it is a self-describing directory: the
 * root lists the services, each
 * service lists its endpoints, and `?endpoint=/path&detail=true` returns the full parameter spec. So
 * **nothing about the endpoint list is hardcoded here** beyond the two paths we actually call. When a
 * call fails, ask the service what it wants rather than guessing at parameter names: the API told us
 * `format` had to be `markdown` and that KvK search takes `q`, both of which we had wrong first try.
 *
 * What earns its place in this project:
 * - `POST /scraper/fetch` renders through a stealth browser, so a Cloudflare-protected site that
 *   answers 403 to a plain fetch comes back as readable markdown. Several prospect sites are exactly that.
 * - `POST /scraper/extract` takes a URL and a field/type map and returns structured data, which is
 *   how a signal and a contact address come out of a site in one call instead of three searches.
 * - `GET /tools/kvk/search?q=` hits the real Dutch business register. A company that is not in the
 *   KvK under the name we hold is a record to fix, not a company to write to.
 *
 * The key is `ALIVE_SECRET_KEY` and it lives in `.env.development`, which is generated by the
 * platform. Never paste it into a file, a note or a commit.
 */
import { readFileSync } from "node:fs"
import { z } from "zod"

/**
 * What each endpoint is expected to answer.
 *
 * These are parsed, not asserted. A remote service is the one boundary where the shape is somebody
 * else's decision and can change without us: reading a field off an unchecked body is how
 * `fetchPage` once returned an empty string for every site and it read as "this company says
 * nothing". A parse that fails names the field, at the call, on the run that broke.
 */
/** A 200 that carries a message is still a refusal. An empty `error` is not one. */
const ErrorBody = z.object({ error: z.string().min(1) })

const PageBody = z.object({
  body: z.string().optional(),
  content: z.string().optional(),
  markdown: z.string().optional(),
  data: z.string().optional(),
})

const ExtractBody = z.object({ data: z.record(z.string(), z.unknown()) })

const KvkResult = z.object({
  kvkNummer: z.string(),
  naam: z.string(),
  adres: z.record(z.string(), z.string()).optional(),
})

const KvkBody = z.object({ resultaten: z.array(KvkResult).optional() })

export type KvkMatch = z.infer<typeof KvkResult>

/**
 * Read one variable out of the generated `.env.development`.
 *
 * The platform writes values quoted (`KEY="value"`), and the earlier regex captured the quotes with
 * it, so this path returned a token that was wrong in a way nothing checked: every request built a
 * malformed bearer header and came back 401. Bun populates `process.env` before any of this runs,
 * which is why it stayed hidden — only a plain `node` invocation reached the fallback.
 */
function fromEnvFile(name: string): string | null {
  try {
    const match = readFileSync(new URL("../../../.env.development", import.meta.url), "utf8").match(
      new RegExp(`^${name}=(.+)$`, "m"),
    )
    const value = match?.[1]
    if (value === undefined) return null
    return value.trim().replace(/^(['"])(.*)\1$/, "$2")
  } catch {
    return null
  }
}

/**
 * The one secret that stays in a file. Everything else this project reads at runtime comes out of
 * the CRM database; this key is what buys access to the services in the first place, so it cannot.
 */
export function serviceKey(): string {
  const key = process.env.ALIVE_SECRET_KEY ?? fromEnvFile("ALIVE_SECRET_KEY")
  if (!key) {
    throw new Error("ALIVE_SECRET_KEY is missing. It is generated into .env.development by the platform.")
  }
  return key
}

/**
 * Where the services live. Config, not a constant: the host was a literal here, and a literal is a
 * value you cannot change without a commit. No default, for the same reason the CRM URL has none.
 */
function base(): string {
  const url = process.env.ALIVE_SERVICES_URL ?? fromEnvFile("ALIVE_SERVICES_URL")
  if (!url) {
    throw new Error("ALIVE_SERVICES_URL is not set. It names the Alive services host and has no default.")
  }
  return url.replace(/\/+$/, "")
}

async function call(path: string, init: RequestInit): Promise<unknown> {
  const res = await fetch(`${base()}${path}`, {
    ...init,
    headers: { authorization: `Bearer ${serviceKey()}`, "content-type": "application/json", ...(init.headers ?? {}) },
  })
  const body = await res.json().catch(() => ({ error: `${res.status} ${res.statusText}` }))
  if (!res.ok || ErrorBody.safeParse(body).success) {
    // Surface the service's own complaint verbatim. It names the field it wanted, which is the
    // difference between a fix and a guess.
    throw new Error(`${path}: ${JSON.stringify(body)}`)
  }
  return body
}

/** Ask a service what it offers. Use this before writing a new call, not after one fails twice. */
export const discover = (service?: string, endpoint?: string) =>
  call(
    `/${service ? `${service}/` : ""}discover${endpoint ? `?endpoint=${encodeURIComponent(endpoint)}&detail=true` : ""}`,
    { method: "GET" },
  )

/** A page as markdown, through a browser that survives Cloudflare. */
export async function fetchPage(url: string): Promise<string> {
  const body = PageBody.parse(
    await call("/scraper/fetch", { method: "POST", body: JSON.stringify({ url, format: "markdown" }) }),
  )
  // The page arrives under `body`. An empty string here once read as "the site says nothing", which
  // is the same failure as reading a 403 as a dead company — so an empty read throws instead.
  const page = body.body ?? body.markdown ?? body.content ?? body.data ?? ""
  if (!page) throw new Error("/scraper/fetch returned no page body — check the response shape before trusting it.")
  return page
}

/**
 * URL plus a field/type map in, structured data out.
 *
 * `maxLength` is how much of the page text reaches the model, and its default of 30 000 characters is
 * the quietest failure this service has. A team page on a modern marketing site runs to 180 000: the
 * people are near the bottom, the read stops a long way above them, and the answer comes back as a
 * confident empty list. Five Amsterdam companies were recorded as naming nobody that way, each of them
 * with a full team page. The documented ceiling is 100 000, so ask for what the page actually needs.
 */
export async function extract(
  url: string,
  schema: Record<string, string>,
  prompt?: string,
  maxLength?: number,
): Promise<Record<string, unknown>> {
  const body = ExtractBody.parse(
    await call("/scraper/extract", { method: "POST", body: JSON.stringify({ url, schema, prompt, maxLength }) }),
  )
  return body.data
}

/** The Dutch business register, by name. Real data, not fixtures. */
export async function kvk(name: string): Promise<KvkMatch[]> {
  const body = KvkBody.parse(await call(`/tools/kvk/search?q=${encodeURIComponent(name)}`, { method: "GET" }))
  return body.resultaten ?? []
}
